# Generated by Django 2.2 on 2021-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210523_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.IntegerField(default=0, verbose_name='Отвечено'),
        ),
    ]
